import sqlite3

conn = sqlite3.connect('icfes.db')
c = conn.cursor()

# Tabla Colegios (todos los campos relacionados)
c.execute('''
CREATE TABLE IF NOT EXISTS Colegios (
    COLE_COD_ICFES TEXT PRIMARY KEY,
    COLE_COD_DANE_INSTITUCION TEXT,
    COLE_NOMBRE_SEDE TEXT,
    COLE_CALENDARIO TEXT,
    COLE_GENERO TEXT,
    COLE_NATURALEZA TEXT,
    COLE_BILINGUE TEXT,
    COLE_JORNADA TEXT,
    COLE_CARACTER TEXT,
    COLE_VALOR_PENSION TEXT
)
''')

# Tabla Estudiantes (datos personales, familia, econ, discapacidades, reprobados, etc.)
c.execute('''
CREATE TABLE IF NOT EXISTS Estudiantes (
    ESTU_CONSECUTIVO TEXT PRIMARY KEY,
    PERIODO TEXT,
    ESTU_TIPODOCUMENTO TEXT,
    ESTU_PAIS_RESIDE TEXT,
    ESTU_GENERO TEXT,
    ESTU_NACIMIENTO_DIA INTEGER,
    ESTU_NACIMIENTO_MES INTEGER,
    ESTU_NACIMIENTO_ANNO INTEGER,
    ESTU_EDAD INTEGER,
    ESTU_LIMITA_BAJAVISION TEXT,
    ESTU_LIMITA_SORDOCEGUERA TEXT,
    ESTU_LIMITA_COGNITIVA TEXT,
    ESTU_LIMITA_INVIDENTE TEXT,
    ESTU_LIMITA_MOTRIZ TEXT,
    ESTU_LIMITA_SORDOINTERPRETE TEXT,
    ESTU_LIMITA_SORDONOINTERPRETE TEXT,
    ESTU_ETNIA TEXT,
    ESTU_COD_RESIDE_MCPIO TEXT,
    ESTU_RESIDE_MCPIO TEXT,
    ESTU_RESIDE_DEPTO TEXT,
    ESTU_ZONA_RESIDE TEXT,
    ESTU_AREA_RESIDE TEXT,
    IND_COD_ICFES_TERMINO TEXT,
    COLE_COD_ICFES TEXT,
    ESTU_VECES_ESTADO INTEGER,
    ESTU_CARRDESEADA_TIPO TEXT,
    ESTU_IES_COD_DESEADA TEXT,
    ESTU_IES_COD_MPIO_DESEADA TEXT,
    ESTU_IES_DEPT_DESEADA TEXT,
    ESTU_IES_DESEADA_NOMBRE TEXT,
    ESTU_IES_MPIO_DESEADA TEXT,
    ESTU_TOTAL_ALUMNOS_CURSO INTEGER,
    ESTU_ANO_MATRICULA_PRIMERO INTEGER,
    ESTU_ANO_TERMINO_QUINTO INTEGER,
    ESTU_ANOS_COLEGIO_ACTUAL INTEGER,
    ESTU_ANO_MATRICULA_SEXTO INTEGER,
    ESTU_ANOS_PREESCOLAR INTEGER,
    ESTU_CUANTOS_COLE_ESTUDIO INTEGER,
    ESTU_REPROBO_CUARTO TEXT,
    ESTU_REPROBO_DECIMO TEXT,
    ESTU_REPROBO_NOVENO TEXT,
    ESTU_REPROBO_OCTAVO TEXT,
    ESTU_REPROBO_PRIMERO TEXT,
    ESTU_REPROBO_QUINTO TEXT,
    ESTU_REPROBO_SEGUNDO TEXT,
    ESTU_REPROBO_SEPTIMO TEXT,
    ESTU_REPROBO_SEXTO TEXT,
    ESTU_REPROBO_TERCERO TEXT,
    ESTU_REPROBO_ONCE_MAS TEXT,
    ESTU_POR_MEJORARPOSICIONSOCIAL TEXT,
    ESTU_POR_COLOMBIAAPRENDE TEXT,
    ESTU_POR_INFLUENCIAALGUIEN TEXT,
    ESTU_POR_INTERESPERSONAL TEXT,
    ESTU_POR_BUSCANDOCARRERA TEXT,
    ESTU_POR_TRADICIONFAMILIAR TEXT,
    ESTU_POR_ORIENTACIONVOCACIONAL TEXT,
    ESTU_RAZON_RETIRO TEXT,
    ESTU_POR_AMIGOSESTUDIANDO TEXT,
    ESTU_POR_COSTOMATRICULA TEXT,
    ESTU_POR_OPORTUNIDADES TEXT,
    ESTU_POR_OTRARAZON TEXT,
    ESTU_PRESTIGIOINSTITUCION TEXT,
    ESTU_POR_UBICACION TEXT,
    ESTU_POR_UNICAQUEOFRECE TEXT,
    ESTU_RETIRARSE_COLEGIO TEXT,
    ESTU_COD_MCPIO_PRESENTACION TEXT,
    ESTU_MCPIO_PRESENTACION TEXT,
    ESTU_DEPTO_PRESENTACION TEXT,
    ESTU_EXAM_NOMBREEXAMEN TEXT,
    FAMI_EDUCA_PADRE TEXT,
    FAMI_EDUCA_MADRE TEXT,
    FAMI_OCUPA_PADRE TEXT,
    FAMI_OCUPA_MADRE TEXT,
    FAMI_ESTRATO_VIVIENDA TEXT,
    FAMI_NIVEL_SISBEN TEXT,
    FAMI_PERSONAS_HOGAR INTEGER,
    FAMI_CUARTOS_HOGAR INTEGER,
    FAMI_PISOSHOGAR TEXT,
    FAMI_TELEFONO_FIJO TEXT,
    FAMI_CELULAR TEXT,
    FAMI_INTERNET TEXT,
    FAMI_SERVICIO_TELEVISION TEXT,
    FAMI_COMPUTADOR TEXT,
    FAMI_LAVADORA TEXT,
    FAMI_NEVERA TEXT,
    FAMI_HORNO TEXT,
    FAMI_DVD TEXT,
    FAMI_MICROONDAS TEXT,
    FAMI_AUTOMOVIL TEXT,
    FAMI_INGRESO_FMILIAR_MENSUAL TEXT,
    ESTU_TRABAJA TEXT,
    ESTU_HORAS_TRABAJA INTEGER,
    FOREIGN KEY (COLE_COD_ICFES) REFERENCES Colegios(COLE_COD_ICFES)
)
''')

# Tabla Puntajes
c.execute('''
CREATE TABLE IF NOT EXISTS Puntajes (
    ESTU_CONSECUTIVO TEXT PRIMARY KEY,
    PUNT_LENGUAJE INTEGER,
    PUNT_MATEMATICAS INTEGER,
    PUNT_C_SOCIALES INTEGER,
    PUNT_FILOSOFIA INTEGER,
    PUNT_BIOLOGIA INTEGER,
    PUNT_QUIMICA INTEGER,
    PUNT_FISICA INTEGER,
    PUNT_INGLES INTEGER,
    DESEMP_INGLES TEXT,
    NOMBRE_COMP_FLEXIBLE TEXT,
    PUNT_COMP_FLEXIBLE INTEGER,
    DESEMP_COMP_FLEXIBLE TEXT,
    ESTU_PUESTO INTEGER,
    FOREIGN KEY (ESTU_CONSECUTIVO) REFERENCES Estudiantes(ESTU_CONSECUTIVO)
)
''')

conn.commit()
conn.close()
print("Base de datos creada con todos los campos.")